networks:
  elastic-network:
    driver: bridge

volumes:
  es-data01:
    driver: local

services:
  # fluent-bit:
  #   container_name: fluent-bit
  #   image: fluent/fluent-bit
  #   volumes:
  #     - ./config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
  #     - ./logfiles:/var/log/test
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - elastic-network
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - ./${CNF_DIR}/jvm.options:/usr/share/elasticsearch/config/jvm.options.d/jvm.options
      - ./${CNF_DIR}/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./${CNF_DIR}/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
      - ./es-data01:/usr/share/elasticsearch/data
    user: ${UID}:${GID}
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    networks:
      - elastic-network
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - ./${CNF_DIR}/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana-data:/usr/share/kibana/data
    user: ${UID}:${GID}
    environment:
      - elasticsearch.username=${KB_USERNAME}
      - elasticsearch.password=${KB_PASSWORD}
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - elastic-network
    depends_on:
      - elasticsearch
