##########################################
## General and Networking
##########################################

server.host: '0.0.0.0'
server.shutdownTimeout: '5s'
monitoring.ui.container.elasticsearch.enabled: true
xpack.screenshotting.browser.chromium.disableSandbox: true

##########################################
## Security
##########################################

elasticsearch.username: 'kibana_system'

##########################################
## Telemetry
##########################################

# opt-out of telemetry
telemetry.allowChangingOptInStatus: false
telemetry.optIn: false

##########################################
## Logging
##########################################

# reduce logging noise - limit to warnings only
logging:
  appenders:
    console_appender:
      type: console
      layout:
        type: pattern
        highlight: true
  root:
    appenders: [console_appender]
    level: info
